# Generated by Django 5.2.11 on 2026-02-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_profile_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
